#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.2-codex"
model_reasoning_effort = "high"
file_opener = "vscode-insiders"
suppress_unstable_features_warning = true

[features]
collaboration_modes = true
