[tools]
# mise
usage = "latest"

# util
prek = "latest"
github-cli = "latest"
chezmoi = "latest"
fzf = "latest"
fd = "latest"
lazygit = "latest"
delta = { version = "latest", repo = "andweeb/asdf-delta" }
